### ISSUE TITLE
bug: event push fails with NullPointerException when no subscriptions found

### ISSUE THREAD

**Issue by mlesikov** [clouway/clouwaypush#26]
fails when no subscriptions

```java
 @Override
  public List<Subscription> findSubscriptions(PushEvent.Type type) {
    log.info("Event type: " + type.getKey());

    final DateTime now = currentDate.get();

    Map<String, Subscription> subscriptions = (Map<String, Subscription>) memcacheService.get(type.getKey());

    List<Subscription> result = Lists.newArrayList();
    for (Subscription each : subscriptions.values()) {
      // Keep alive ensures that these entries will be deleted.
      if (each.isActive(now)) {
        result.add(each);
      }
    }

    return result;
  }
```

```java
java.lang.NullPointerException
	at com.clouway.push.server.MemcacheSubscriptionsRepository.findSubscriptions(MemcacheSubscriptionsRepository.java:97)
	at com.clouway.push.server.PushServiceImpl.pushEvent(PushServiceImpl.java:48)
	at com.clouway.push.server.PushServiceImpl.pushEvent(PushServiceImpl.java:33)
```

**Comment by mgenov** [comment]
Does this happen when subscriptions are expired from memcache or user is not having any subscriptions?
